In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
x = np.arange(5,10,2)

In [51]:
y = np.ones((3,2,5))
np.transpose(y, (1,0,2)).shape

(2, 3, 5)

In [52]:
y

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [31]:
y[1] = np.arange(4,10).reshape(2,3)
y[2] = np.arange(-5,1).reshape(2,3)

In [32]:
y

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[-5., -4., -3.],
        [-2., -1.,  0.]]])

In [45]:
y.flatten()

array([ 1.,  1.,  1.,  1.,  1.,  1.,  4.,  5.,  6.,  7.,  8.,  9., -5.,
       -4., -3., -2., -1.,  0.])

In [46]:
axe.flatten()

array([ 1.,  1.,  1.,  4.,  5.,  6., -5., -4., -3.,  1.,  1.,  1.,  7.,
        8.,  9., -2., -1.,  0.])

In [56]:
axe = np.transpose(y, (1,0,2))
axe.shape

(2, 3, 5)

In [24]:
np.transpose(y, (1,0,2)).shape

(2, 3, 3)

In [36]:
np.transpose(y)

array([[[ 1.,  4., -5.],
        [ 1.,  7., -2.]],

       [[ 1.,  5., -4.],
        [ 1.,  8., -1.]],

       [[ 1.,  6., -3.],
        [ 1.,  9.,  0.]]])

In [37]:
np.transpose(y).shape

(3, 2, 3)

In [38]:
y.shape

(3, 2, 3)

In [39]:
y.strides

(48, 24, 8)

In [41]:
axe.strides

(24, 48, 8)

In [54]:
x = np.ones((480, 640, 3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])